### ISSUE TITLE
Remove at ratio

### ISSUE THREAD

**Issue by FVGAZI** [ratanakvlun/deluge-labelplus#16]
Hi,
 The remove at ratio function does not work for me. It worked once when I changed the ratio and hit apply, but then never again. Anything I can do to resolve this on my end?

**Comment by ratanakvlun** [comment]
How are you using it and what are your expectations?

Remove at ratio is part of the stop seed at ratio functionality. It only applies to torrents that are being seeded and not torrents that are complete and paused but have exceeded the ratio.

**Comment by jesseeverhart** [comment]
It seems to be related to Sonarr. The remove function works as it should with torrents that are added manually. Not sure if it's something that I can fix, but I do appreciate you responding.

**Comment by ratanakvlun** [comment]
Installed Sonarr just to see for myself. I can confirm that remove at ratio is not enabled for torrents added by Sonarr. Not sure what it's doing differently though.

**Comment by jesseeverhart** [comment]
Interesting. If you figure it out let me know. I'll do the same.

**Comment by ratanakvlun** [comment]
Dug a little deeper into this. Looks like Sonarr is explictly setting remove at ratio to false and since it happens after LabelPlus loads options for a torrent, it overrides the LabelPlus setting. Not sure about their reasoning, so you'd have to ask them.

Reference: https://github.com/Sonarr/Sonarr/blob/v2.0.0.4230/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L65

**Comment by jesseeverhart** [comment]
I will ask them. Your plugin puts the torrents in a paused state at a set ratio. So if it has to be that way, it's good enough. I appreciate your help. I'll let you know if I get anywhere with the Sonarr people.
